spring:
  flyway:
    schemas: projectsTodo
    create-schemas: true
    url: jdbc:mariadb://localhost:3307/
    user: root
    password: iamgroot
  datasource:
    url: jdbc:mariadb://localhost:3307/projectsTodo
    username: root
    password: iamgroot

